AWSTemplateFormatVersion: '2010-09-09'
Description: Nested stack launcher for 3-tier web application infrastructure

Parameters:
  TemplateBucket:
    Type: String
    Description: S3 bucket where all modular CloudFormation templates are stored

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}/networking/vpc.yaml"

  IGWRouteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}/networking/igw-routing.yaml"

  NATRouteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}/networking/nat-routing.yaml"

  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}/security/security-groups.yaml"

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}/storage/s3.yaml"

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}/compute/ec2-asg-alb.yaml"

  RDSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${TemplateBucket}/database/rds.yaml"
